# Send prefix
unbind-key C-b
set -g prefix C-a
bind C-a send-prefix
bind a last-window

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# Mouse mode
set -g mouse on

# Easy config reload
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded."

# set -g default-terminal "xterm-256color"
# set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @rose_pine_variant 'dawn'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
